// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParam) Reset()         { *m = NoParam{} }
func (m *NoParam) String() string { return proto.CompactTextString(m) }
func (*NoParam) ProtoMessage()    {}
func (*NoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_95ca2ad3f55a58e3, []int{0}
}

func (m *NoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParam.Unmarshal(m, b)
}
func (m *NoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParam.Marshal(b, m, deterministic)
}
func (m *NoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParam.Merge(m, src)
}
func (m *NoParam) XXX_Size() int {
	return xxx_messageInfo_NoParam.Size(m)
}
func (m *NoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParam.DiscardUnknown(m)
}

var xxx_messageInfo_NoParam proto.InternalMessageInfo

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95ca2ad3f55a58e3, []int{1}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95ca2ad3f55a58e3, []int{2}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NamesList struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamesList) Reset()         { *m = NamesList{} }
func (m *NamesList) String() string { return proto.CompactTextString(m) }
func (*NamesList) ProtoMessage()    {}
func (*NamesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_95ca2ad3f55a58e3, []int{3}
}

func (m *NamesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamesList.Unmarshal(m, b)
}
func (m *NamesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamesList.Marshal(b, m, deterministic)
}
func (m *NamesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamesList.Merge(m, src)
}
func (m *NamesList) XXX_Size() int {
	return xxx_messageInfo_NamesList.Size(m)
}
func (m *NamesList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamesList.DiscardUnknown(m)
}

var xxx_messageInfo_NamesList proto.InternalMessageInfo

func (m *NamesList) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type MessagesList struct {
	Messages             []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesList) Reset()         { *m = MessagesList{} }
func (m *MessagesList) String() string { return proto.CompactTextString(m) }
func (*MessagesList) ProtoMessage()    {}
func (*MessagesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_95ca2ad3f55a58e3, []int{4}
}

func (m *MessagesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesList.Unmarshal(m, b)
}
func (m *MessagesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesList.Marshal(b, m, deterministic)
}
func (m *MessagesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesList.Merge(m, src)
}
func (m *MessagesList) XXX_Size() int {
	return xxx_messageInfo_MessagesList.Size(m)
}
func (m *MessagesList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesList.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesList proto.InternalMessageInfo

func (m *MessagesList) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*NoParam)(nil), "greet_service.NoParam")
	proto.RegisterType((*HelloRequest)(nil), "greet_service.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "greet_service.HelloResponse")
	proto.RegisterType((*NamesList)(nil), "greet_service.NamesList")
	proto.RegisterType((*MessagesList)(nil), "greet_service.MessagesList")
}

func init() {
	proto.RegisterFile("proto/greet.proto", fileDescriptor_95ca2ad3f55a58e3)
}

var fileDescriptor_95ca2ad3f55a58e3 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x89, 0xff, 0xba, 0xbe, 0x74, 0x07, 0x5f, 0x44, 0xcb, 0x14, 0x99, 0x39, 0x55, 0x0f,
	0xdd, 0xd0, 0x2f, 0x20, 0xf3, 0xa0, 0x07, 0x1d, 0xd2, 0x82, 0x07, 0x2f, 0x23, 0xce, 0x97, 0x12,
	0x68, 0x9b, 0x99, 0x44, 0xc1, 0x2f, 0xeb, 0x67, 0x91, 0xa6, 0x8d, 0x63, 0x43, 0x76, 0xda, 0x29,
	0xef, 0x13, 0x9e, 0xf7, 0xc7, 0xf3, 0x84, 0xc0, 0xe1, 0x42, 0x2b, 0xab, 0x46, 0x85, 0x26, 0xb2,
	0xa9, 0x9b, 0xb1, 0xef, 0xc4, 0xcc, 0x90, 0xfe, 0x92, 0x73, 0xe2, 0x21, 0x04, 0x53, 0xf5, 0x2c,
	0xb4, 0xa8, 0x38, 0x87, 0xe8, 0x81, 0xca, 0x52, 0x65, 0xf4, 0xf1, 0x49, 0xc6, 0x22, 0xc2, 0x5e,
	0x2d, 0x2a, 0x8a, 0xd9, 0x90, 0x25, 0x61, 0xe6, 0x66, 0x7e, 0x09, 0xfd, 0xce, 0x63, 0x16, 0xaa,
	0x36, 0x84, 0x31, 0x04, 0x15, 0x19, 0x23, 0x0a, 0xef, 0xf3, 0x92, 0x5f, 0x40, 0x38, 0x15, 0x15,
	0x99, 0x47, 0x69, 0x2c, 0x1e, 0xc1, 0x7e, 0xb3, 0x6f, 0x62, 0x36, 0xdc, 0x4d, 0xc2, 0xac, 0x15,
	0xfc, 0x0a, 0xa2, 0xa7, 0xd6, 0xdd, 0xba, 0x06, 0xd0, 0xeb, 0xb6, 0xbd, 0xf1, 0x4f, 0x5f, 0xff,
	0xec, 0x40, 0x74, 0xdf, 0x44, 0xcf, 0xdb, 0xe4, 0x78, 0x0b, 0xbd, 0x5c, 0x7c, 0xbb, 0x34, 0x78,
	0x9c, 0xae, 0xb4, 0x4a, 0xbb, 0x4a, 0x83, 0xb3, 0xb5, 0xfb, 0xd5, 0xec, 0x39, 0x9c, 0x78, 0x42,
	0x03, 0x25, 0x9d, 0x5b, 0x4d, 0xa2, 0x92, 0x75, 0x81, 0xf1, 0x3a, 0xd0, 0x37, 0xd9, 0x8c, 0x1c,
	0x33, 0x7c, 0x59, 0x42, 0xef, 0x4a, 0x49, 0xb5, 0x5d, 0x42, 0x4f, 0xff, 0x5f, 0x75, 0xaf, 0xbd,
	0x99, 0x9b, 0x30, 0x9c, 0xc1, 0xb9, 0xe7, 0x4e, 0xe4, 0xbb, 0xd4, 0x34, 0xb7, 0x52, 0xd5, 0xa2,
	0xdc, 0x0e, 0x7e, 0xcc, 0x26, 0xe1, 0x6b, 0x90, 0x8e, 0xdc, 0x1f, 0x79, 0x3b, 0x70, 0xc7, 0xcd,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x2d, 0xfc, 0x6d, 0x3f, 0x02, 0x00, 0x00,
}
